### ISSUE TITLE
[Documentation] .env

### ISSUE THREAD

**Issue by psavvaidis** [wspr-ncsu/visiblev8#67]
## The issue
There isn't any example of env file with the variables used by the engine. Documentation suggests the reader to look through the source code, which is not very efficient

## The Proposal
Add a list and description of the env variables in the documentation and an .env.example file in the source code

**Comment by sohomdatta1** [comment]
> ## The issue
> There isn't any example of env file with the variables used by the engine. Documentation suggests the reader to look through the source code, which is not very efficient
> 
> ## The Proposal
> Add a list and description of the env variables in the documentation and an .env.example file in the source code

Which .env file is this ?

**Comment by psavvaidis** [comment]
Hey @sohomdatta1 ,

 Unfortunately, there isn't any .env file.
